# Generated by Django 2.1 on 2018-08-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restservice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='amount',
        ),
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.PositiveIntegerField(choices=[(0, 'AUTH'), (1, 'PRSNT')], default=0, verbose_name='Currency'),
        ),
    ]
