# Generated by Django 2.1 on 2018-08-07 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restservice', '0004_auto_20180806_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='transaction_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_id', to='restservice.Transaction', verbose_name='Transaction_Id'),
        ),
    ]
