# Generated by Django 2.1 on 2018-08-07 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restservice', '0006_auto_20180807_0922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='mercant_city',
            new_name='merchant_city',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='mercant_country',
            new_name='merchant_country',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='mercant_name',
            new_name='merchant_name',
        ),
    ]
