# Generated by Django 2.1 on 2018-08-07 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restservice', '0007_auto_20180807_0923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='amount',
            new_name='transaction_amount',
        ),
    ]
