# Generated by Django 2.1 on 2018-08-09 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restservice', '0009_auto_20180807_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='transfer_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Transfer Amount'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='transfer_destination_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_destination_account', to='restservice.Account', verbose_name='Transfer Destination Account'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='transfer_source_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_source_account', to='restservice.Account', verbose_name='Transfer Source Account'),
        ),
    ]
