# Generated by Django 2.1 on 2018-08-14 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restservice', '0010_auto_20180809_0756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='merchant_city',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='merchant_country',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='merchant_name',
        ),
    ]
